### ISSUE TITLE
Issues installing

### ISSUE THREAD

**Issue by mcinnes01** [monteslu/node-red-contrib-gpio#1]
Hi

I am having trouble when trying to install this on my server that is running node-red, I am running on a server 2012 r2 VM.

This is the error:

> serialport@1.6.3 install C:\Program Files\nodejs\node_modules\node-red\node_modules\node-red-contrib-gpio\node_modules\serialport
> node-pre-gyp install --fallback-to-build

Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it is installed elsewhere.  [C:\Program Files\nodejs\node_modules\node-red\node_modules\node-red-contrib-gpio\node_modules\serialport\build\binding.sln]
Failed to execute 'C:\Program Files\nodejs\node.exe rebuild --name=serialport --configuration=Release --module_name=serialport --version=1.6.3 --major=1 --minor=6 --patch=3 --runtime=node --node_abi=node-v11 --platform=win32 --target_platform=win32 --arch=x64 --target_arch=x64 --module_main=./serialport --host=https://node-serialport.s3.amazonaws.com/ --module_path=C:\Program Files\nodejs\node_modules\node-red\node_modules\node-red-contrib-gpio\node_modules\serialport\build\serialport\v1.6.3\Release\node-v11-win32-x64 --remote_path=./serialport/v1.6.3/Release/ --package_name=node-v11-win32-x64.tar.gz --staged_tarball=build\stage\serialport\v1.6.3\Release\node-v11-win32-x64.tar.gz --hosted_path=https://node-serialport.s3.amazonaws.com/serialport/v1.6.3/Release/ --hosted_tarball=https://node-serialport.s3.amazonaws.com/serialport/v1.6.3/Release/node-v11-win32-x64.tar.gz' (1)

I have tried with various versions of  Visual C++ component, adding the .Net 2 - 3.5 feature, various versions of python and reinstalling the lot but to no avail. Do you have any guidance how I might resolve this issue?

Many thanks

Andy

**Comment by mcinnes01** [comment]
I removed node, python and vs completely, restarted, installed python, vs 2013 express, node in that order and everything worked.

**Comment by monteslu** [comment]
awesome.  Thanks for the follow up.
