### ISSUE TITLE
Nodes not showing in menu

### ISSUE THREAD

**Issue by tcudaback** [monteslu/node-red-contrib-gpio#24]
Every thing installed with no errors. New nodes are not in the menu. They are listed in the palette manager but are greyed out. What am I missing?

**Comment by monteslu** [comment]
@tcudaback are you getting any errors in the console?

**Comment by tcudaback** [comment]
Nothing that I noticed. I'll fire it up again. No errors noted.
Update: Did a fresh install, now working.
