### ISSUE TITLE
Could anyone share an example for beaglebone?

### ISSUE THREAD

**Issue by bh4rtp** [monteslu/node-red-contrib-gpio#29]
i have installed gpio node. but cannot find any document on how to use it. can anyone share an example for beaglebone? node-red exported json text is preferred.

**Comment by monteslu** [comment]
This is for raspberry pi and a bit out of date the, but the concept is still the same:  https://github.com/rwaldron/johnny-five/wiki/Getting-started-with-Raspberry-Pi-node-red-and-IoT

The main thing is that you need https://www.npmjs.com/package/beaglebone-io installed and to select beaglebone-io as the io plugin when creating the nodebot instance.
