### ISSUE TITLE
PWM frequency 

### ISSUE THREAD

**Issue by badfrogg** [monteslu/node-red-contrib-gpio#31]
Can you explain how the PWM frequency is set Please? I have PWM in use on a Beaglebone Black and have no problem controlling the duty cycle but the frequency is at 2khz and I need to increase it to something above the audible range.

**Comment by monteslu** [comment]
so a little background,
this project mostly just utilizes johnny-five under the hood.  Johnny-five started out with Arduino support over serial cables using the firmata protocol.  This gives us a bunch of apis like pwmWrite() which gives us a way to set the duty cycle, but not the frequency.  The frequency is determined under the hood by the IO plugin johnny-five is using.  In this case https://github.com/julianduque/beaglebone-io

I'm not sure if there's hardware APIs you can use to customize beaglebone-io for frequency, but if you can, you can use an edited/forked beaglebone-io with node-red-contrib-gpio and have access to the `io` variable in the johnny-five node.

**Comment by badfrogg** [comment]
Thanks for that explanation. I was trying to read your source code and was kinda seeing that but my JavaScript is still very amateur.

**Comment by Ch3fk0ch88** [comment]
Did someone found a way to change the frequency?
