### ISSUE TITLE
Is this repository dead?

### ISSUE THREAD

**Issue by lbineau** [monteslu/node-red-contrib-gpio#44]
Hello dear maintainers,

I would like what's the status of this repository.
Especially Johnny-Five is now with version 2.x, do you have any plan to upgrade this library to support it?

Thank you.

**Comment by monteslu** [comment]
PR's accepted for that :)

**Comment by lbineau** [comment]
Thank you for the quick answer. 
I'm not likely to contribute to this repository, I just wanted to know what is the status of the repo but it is good to know the author is still around :-)
